name: Gradle Package

on:
  push:
    tags:
      - '*'

jobs:
  changelog:
    name: Generate changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Generate changelog
        run: ./gradlew getChangelog --project-version ${{ github.ref_name }} --output-file ./changelog.out.md

      - name: Upload changelog
        uses: actions/upload-artifact@v4
        with:
          name: changelog
          path: ./changelog.out.md
          retention-days: 5

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [ changelog ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload build output (libs)
        uses: actions/upload-artifact@v4
        with:
          name: libs
          path: build/libs/

      - name: Upload build output (devlibs)
        uses: actions/upload-artifact@v4
        with:
          name: devlibs
          path: build/devlibs/

  release:
    permissions:
      contents: write
    name: Create a release
    runs-on: ubuntu-latest
    needs: [ changelog, build ]

    steps:
      - name: Download changelog
        uses: actions/download-artifact@v4
        with:
          name: changelog

      - name: Download libs
        uses: actions/download-artifact@v4
        with:
          name: libs
          path: build/libs/

      - uses: Kir-Antipov/mc-publish@v3.3
        with:
          # Only include this section if you wish to publish
          # your assets on Modrinth.
          modrinth-id: super-duper-mod
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          changelog-file: changelog.out.md
          version-type: release
          github-draft: true

          # Only include this section if you wish to publish
          # your assets on GitHub.
          github-token: ${{ secrets.GITHUB_TOKEN }}
